# serverless.yml

service: my-express-application

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  memorySize: 512
  timeout: 20
  apiKeys:
    - ${$self:stage}-apiKey
  usagePlan:
    throttle:
      burstLimit: 1
      rateLimit: 1

plugins:
  - serverless-offline

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    concurrency: 1